spring:
  datasource:
    name: testDateBase
    url: jdbc:mysql://localhost:3306/ers?&characterEncoding=utf-8&useUnicode=true&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

  jackson:
    date-format: "yyyy-MM-dd HH:mm:ss"
    time-zone: "GMT+8"

  #thymeleaf 配置
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    #缓存设置为false, 这样修改之后马上生效，便于调试
    cache: false
    servlet:
      content-type: text/html

  #发送邮件配置
  mail:
    host: smtp.163.com
    username: smart_ERS@163.com
    password: HJWMULRPJKPGMASF


#配置tomcat服务器
server:
  port: 8080
  servlet:
    context-path: "/"
  #禁用空白（错误）页面，同时添加发生错误时要调用的自定义路径
  error:
    path: "/error"
    whitelabel:
      enabled: false


#Mybatis优化配置
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.example.ers.entity
  configuration:
    map-underscore-to-camel-case: true  #驼峰命名法自动转换

#Mybatis分页工具
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  page-size-zero: true

#控制台看到执行的SQL语句
logging:
  level:
    com:
      example:
        ers:
          mapper: debug