spring:
  datasource:
    name: testDateBase
    url: jdbc:mysql://localhost:3306/ers?&characterEncoding=utf-8&useUnicode=true&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

  jackson:
    date-format: "yyyy-MM-dd HH:mm:ss"
    time-zone: "GMT+8"

  #thymeleaf 配置
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    #缓存设置为false, 这样修改之后马上生效，便于调试
    cache: false
    servlet:
      content-type: text/html


#配置tomcat服务器
server:
  port: 8080
  servlet:
    context-path: "/"

#mybatis优化配置
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.example.ers.entity
  configuration:
    map-underscore-to-camel-case: true  #驼峰命名法自动转换


logging:
  level:
    com:
      example:
        ers:
          mapper: debug